### ISSUE TITLE
[Feature request] Boilerplate for Electron + Vue + Typescript 

### ISSUE THREAD

**Issue by algil** [CKGrafico/Frontend-Boilerplates#38]
Hi! Great repo!!

Would you mind create a boilerplate using electron + vue + typescript? I'm using this project https://github.com/SimulatedGREG/electron-vue for that, but it's not compatible with typescript.

Thanks!

**Comment by CKGrafico** [comment]
We are creating one with Nuxt now, this will take time!

**Comment by algil** [comment]
Ok, Thanks a lot!

**Comment by CKGrafico** [comment]
Let's do this

**Comment by CKGrafico** [comment]
I think that this template is the best you will find https://github.com/SimulatedGREG/electron-vue/ if is still not enough we can do a new one
